title: DataGeeks blog
description: My blogs related to Data Science, Data Engineering and analytics. I might also add some reviews of math, engineering and physics books I read occasionally. So basically everything I geek out about!

# Theme Settings
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme

# UI Settings
show_downloads: false
google_analytics:
