title: DataGeeks blog
description: My blogs related to Data Science, Data Engineering and analytics. I might also add some reviews of math, engineering and physics books I read occasionally. So basically everything I geek out about!
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
show_downloads: ["true" or "false" (unquoted) to indicate whether to provide a download URL]
google_analytics: [Your Google Analytics tracking ID]
